{
 "title": "Scan-Exporter / Internals",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap / Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}",
     "legendFormat": "Heap allocations"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}",
     "legendFormat": "Heap inuse"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}",
     "legendFormat": "Heap idle"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}",
     "legendFormat": "Stack inuse"
    }
   ]
  },
  {
   "title": "Heap allocated",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}",
     "legendFormat": "Heap allocated"
    }
   ]
  },
  {
   "title": "Heap in use",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  {
   "title": "Stack in use",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  {
   "title": "Max allocated heap",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  {
   "title": "Max inuse heap",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  {
   "title": "Mean allocated heap",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  {
   "title": "Mean inuse heap",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "scanexporter_uptime_sec" }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"apps/scanexporter-scan-exporter-chart\"}"
    }
   ]
  },
  { "title": "Promhttp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP 200",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"apps/scanexporter-scan-exporter-chart\", code=\"200\"}",
     "legendFormat": "HTTP 200"
    }
   ]
  },
  {
   "title": "HTTP 500",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"apps/scanexporter-scan-exporter-chart\", code=\"500\"}",
     "legendFormat": "HTTP 500"
    }
   ]
  },
  {
   "title": "HTTP 503",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"apps/scanexporter-scan-exporter-chart\", code=\"503\"}",
     "legendFormat": "HTTP 503"
    }
   ]
  }
 ]
}