{
 "title": "Scan-Exporter / Scans",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(scanexporter_open_ports_total, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of targets",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scanexporter_targets_number_total"
    }
   ]
  },
  {
   "title": "Open ports",
   "type": "graph",
   "description": "Number of ports that are open for each target.",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_open_ports_total >= 1",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Unexpected open ports",
   "type": "graph",
   "description": "Number of ports that are open, and shouldn't be, for each target.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_unexpected_open_ports_total >= 1",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Pending scans",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "scanexporter_pending_scans" }
   ]
  },
  {
   "title": "ICMP not responding",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scanexporter_icmp_not_responding_total"
    }
   ]
  },
  {
   "title": "Unexpected closed ports",
   "type": "graph",
   "description": "Number of ports that are closed, and shouldn't be, for each target.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_unexpected_closed_ports_total >= 1",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Evolution of ports states",
   "type": "graph",
   "description": "Number of ports that are in a different state from previous scan, for each target.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_diff_ports_total >= 1",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  { "title": "Target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Open ports",
   "type": "stat",
   "description": "Number of ports that are open for each target.",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scanexporter_open_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Open ports",
   "type": "graph",
   "description": "Number of ports that are open for each target.",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_open_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Unexpected open ports",
   "type": "stat",
   "description": "Number of ports that are open, and shouldn't be, for each target.",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scanexporter_unexpected_open_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Unexpected open ports",
   "type": "graph",
   "description": "Number of ports that are open, and shouldn't be, for each target.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_unexpected_open_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Unexpected closed ports",
   "type": "stat",
   "description": "Number of ports that are closed, and shouldn't be, for each target.",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scanexporter_unexpected_closed_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Unexpected closed ports",
   "type": "graph",
   "description": "Number of ports that are closed, and shouldn't be, for each target.",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_unexpected_closed_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Evolution of ports states",
   "type": "stat",
   "description": "Number of ports that are in a different state from previous scan, for each target.",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scanexporter_diff_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  },
  {
   "title": "Evolution of ports states",
   "type": "graph",
   "description": "Number of ports that are in a different state from previous scan, for each target.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scanexporter_diff_ports_total{name=\"$target\"}",
     "legendFormat": "{{name}} ({{ip}})"
    }
   ]
  }
 ]
}